### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

### ISSUE THREAD

**Issue by Sa3doon** [tonykipkemboi/ollama_pdf_rag#14]
Hi,

I'm receiving this error in this while loading the PDF in this step

`with open(path, "wb") as f:
        f.write(file_upload.getvalue())
        logger.info(f"File saved to temporary path: {path}")
        loader = UnstructuredPDFLoader(path)
        data = loader.load()`

The full error:
`Uncaught app exception
Traceback (most recent call last):
  File "C:\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Python311\Lib\http\client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1058, in _send_output
    self.send(msg)
  File "C:\Python311\Lib\http\client.py", line 996, in send
    self.connect()
  File "C:\Python311\Lib\http\client.py", line 1475, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\Python311\Lib\ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\pages\04_⚙️_data_ingestion.py", line 281, in <module>
    main()
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\pages\04_⚙️_data_ingestion.py", line 226, in main
    st.session_state["vector_db"] = create_vector_db(file_upload)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\pages\04_⚙️_data_ingestion.py", line 84, in create_vector_db
    data = loader.load()
           ^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\langchain_core\document_loaders\base.py", line 30, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\langchain_community\document_loaders\unstructured.py", line 89, in lazy_load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\langchain_community\document_loaders\pdf.py", line 74, in _get_elements
    return partition_pdf(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\documents\elements.py", line 593, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\file_utils\filetype.py", line 429, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\file_utils\filetype.py", line 385, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\chunking\dispatch.py", line 74, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\partition\pdf.py", line 208, in partition_pdf
    return partition_pdf_or_image(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\partition\pdf.py", line 355, in partition_pdf_or_image
    out_elements = _process_uncategorized_text_elements(elements)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\partition\pdf.py", line 930, in _process_uncategorized_text_elements
    new_el = element_from_text(cast(Text, el).text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\partition\text.py", line 295, in element_from_text
    elif is_possible_narrative_text(text):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\partition\text_type.py", line 80, in is_possible_narrative_text
    if exceeds_cap_ratio(text, threshold=cap_threshold):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\partition\text_type.py", line 276, in exceeds_cap_ratio
    if sentence_count(text, 3) > 1:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\partition\text_type.py", line 225, in sentence_count
    sentences = sent_tokenize(text)
                ^^^^^^^^^^^^^^^^^^^
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\nlp\tokenize.py", line 136, in sent_tokenize
    _download_nltk_packages_if_not_present()
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\nlp\tokenize.py", line 130, in _download_nltk_packages_if_not_present
    download_nltk_packages()
  File "C:\PythonCode\Chatbot\ollama_streamlit_demos\Lib\site-packages\unstructured\nlp\tokenize.py", line 88, in download_nltk_packages
    urllib.request.urlretrieve(NLTK_DATA_URL, tgz_file_path)
  File "C:\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
`

**Comment by Sa3doon** [comment]
@tonykipkemboi Thanks for your reply.

I'm using it on Streamlit app. 

I have created a new virtual environment and installed the all the packages from the requirements file, but unfortunately the same SSL issue is still happening.

by the way, after installing the requirements file there was issue with onnx package while loading a DLL file "DLL load failed while importing onnx_cpp2py_export", after searching it I downgraded its version to 1.16.1 and it fixed the DDL file issue.
